# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_labour_association', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='name1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
