# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-07 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20170507_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Contact'),
        ),
        migrations.AlterField(
            model_name='case',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Location'),
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.TypeOfCase'),
        ),
    ]
