# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20170507_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('pin_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Pin Code')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=20, verbose_name='State')),
            ],
        ),
    ]
