# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_postalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='postalcode',
            name='post_office',
            field=models.CharField(blank=True, max_length=40, verbose_name='Post Office'),
        ),
    ]
